# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scrape_pb2 as scrape__pb2


class CrawlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.process_hyperlinks = channel.unary_unary(
                '/routeguide.Crawl/process_hyperlinks',
                request_serializer=scrape__pb2.Data.SerializeToString,
                response_deserializer=scrape__pb2.Message.FromString,
                )


class CrawlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def process_hyperlinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'process_hyperlinks': grpc.unary_unary_rpc_method_handler(
                    servicer.process_hyperlinks,
                    request_deserializer=scrape__pb2.Data.FromString,
                    response_serializer=scrape__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routeguide.Crawl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Crawl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def process_hyperlinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routeguide.Crawl/process_hyperlinks',
            scrape__pb2.Data.SerializeToString,
            scrape__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
